package vuelos;

public enum EstadoVuelo {
	EN_VUELO, 
	ESPERANDO_PISTA_A, 
	ESPERANDO_PISTA_D, 
	ESPERANDO_ATERRIZAJE, 
	ESPERANDO_DESPEGUE, 
	ATERRIZADO, 
	EMBARQUE, 
	DESEMBARQUE_INI, 
	DESEMBARQUE_FIN,
	CARGA, 
	DESCARGA_INI, 
	DESCARGA_FIN, 
	EN_TIEMPO, 
	RETRASADO, 
	OPERATIVO, 
	EN_HANGAR;
}
